[package]
name = "avatar-bind-studio"
version = "0.1.0"
edition = "2024"
description = "A friendly button_config.ini editor for Avatar Legends: The Fighting Game"

[dependencies]
eframe = { version = "0.35.0", default-features = false, features = ["default_fonts", "glow"] }
rfd = "0.17.2"

[profile.release]
lto = "thin"
opt-level = 2
strip = true
